---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-rolebinding
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: default
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deploy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-deploy-service
  template:
    metadata:
      labels:
        app: k8s-deploy-service
    spec:
      serviceAccountName: deployer
      containers:
      - name: k8s-deploy-service
        image: k8s-deploy-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-deploy-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: k8s-deploy-service
  ports:
    - port: 8000
      targetPort: 8000