apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deploy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-deploy-service
  template:
    metadata:
      labels:
        app: k8s-deploy-service
    spec:
      serviceAccountName: deployer
      containers:
      - name: k8s-deploy-service
        image: k8s-deploy-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000