apiVersion: v1
kind: Service
metadata:
  name: k8s-deploy-service
spec:
  type: NodePort
  selector:
    app: k8s-deploy-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000 